# Generated by Django 5.1.1 on 2024-10-01 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0004_blogpost_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='blog_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blogpost.blogpost'),
        ),
    ]
